##2.2. 数据操作
  &emsp;&emsp;在深度学习中，我们通常会频繁地对数据进行操作。作为动手学深度学习的基础，本节将介绍如何对内存中的数据进行操作。\
  &emsp;&emsp;Tensorflow的主要数据结构是张量，它用张量来操作计算图。在Tensorflow里可以把变量或者占位符声明为张量。张量在Tensorflow中使用类Tensor表示，是存储和变换数据的主要工具。通常将Tensor的实例直接称作张量或者N维数组。如果你之前使用过Numpy，你会发现Tensor和Numpy的多维数组非常类似。然而，Tensor提供GPU计算和自动求梯度等更多功能，这些使Tensor更加适合深度学习。
###2.2.1. 创建Tensor
&emsp;&emsp;我们首先介绍如何创建Tensor。首先导入Tensorflow,这里tf是Tensorflow的缩写。





In [0]:
import tensorflow as tf
tf.enable_eager_execution() #tensorflow1.x默认创建静态图，使用该函数开启动态图模式

&emsp;&emsp;然后我们用range函数创建一个行向量。

In [0]:
x=tf.range(12)
x

<tf.Tensor: id=3, shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

&emsp;&emsp;这时返回了一个Tensor实例，其中包含了从0开始的12个连续整数。从打印x时显示的属性<<tf.Tensor: id=3, shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)> shape=(12,) dtype=int32>可以看出该张量的shape为12和数据类型为int32.\
可以通过shape属性来获取Tensor实例的形状。

In [0]:
x.shape

TensorShape([Dimension(12)])

&emsp;&emsp;也可以通过tf.size()函数得到Tensor实例中元素(element)的总数

In [0]:
tf.size(x)

<tf.Tensor: id=4, shape=(), dtype=int32, numpy=12>

&emsp;&emsp;下面使用tf.reshape函数把行向量x的形状改为(3,4)，也就是一个3行4列的矩阵，并记作X。除了形状改变之外，X中的元素保持不变。

In [0]:
X=tf.reshape(x,shape=[3,4])
X

<tf.Tensor: id=6, shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

&emsp;&emsp;注意X属性中的形状发生了变化。上面tf.reshape(x,shape=[3,,4)也可写成tf.reshape(x,shape=(-1,4))或tf.shape(x,shape=(3,-1))。由于x的元素个数是已知的，这里的-1是能够通过元素个数和其他维度的大小推断出来的。\
&emsp;&emsp;接下来，我们创建一个各元素为0，形状为(2，3，4)的张量。实际上，之前创建的向量和矩阵都是特殊的张量。

In [0]:
tf.zeros((2,3,4))

<tf.Tensor: id=9, shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

&emsp;&emsp;类似地，我们可以创建各元素为1的张量

In [0]:
tf.ones(shape=[3,4])

<tf.Tensor: id=12, shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

&emsp;&emsp;我们也可以通过python的列表(list)指定需要创建的Tensor中的每个元素的指

In [0]:
Y=tf.constant([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
Y

<tf.Tensor: id=13, shape=(3, 4), dtype=int32, numpy=
array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]], dtype=int32)>

&emsp;&emsp;有些情况下，我们需要随机生成Tensor中每个元素的值。下面我们创建一个形状为(3,4)的Tensor。它的每个元素都随机采样于均值为0、标准差为1的正态分布。

In [0]:
tf.random_normal(shape=(3,4),mean=0,stddev=1)

<tf.Tensor: id=19, shape=(3, 4), dtype=float32, numpy=
array([[-1.2910938 , -0.30386716, -2.4718    , -0.0635076 ],
       [-1.081826  , -1.44281   , -1.6498157 , -1.4252629 ],
       [-0.44402036,  0.30663785,  0.41076335,  1.9531201 ]],
      dtype=float32)>

###2.2.2. 张量运算
&emsp;&emsp;tensorflow支持大量的运算符。例如，我们可以对之前创建的两个shape为(3,4)的Tensor做按元素加法。所得结果shape不变。

In [0]:
X,Y,X+Y

(<tf.Tensor: id=6, shape=(3, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=int32)>,
 <tf.Tensor: id=13, shape=(3, 4), dtype=int32, numpy=
 array([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]], dtype=int32)>,
 <tf.Tensor: id=20, shape=(3, 4), dtype=int32, numpy=
 array([[ 2,  2,  6,  6],
        [ 5,  7,  9, 11],
        [12, 12, 12, 12]], dtype=int32)>)



&emsp;&emsp;按元素乘法:



In [0]:
X*Y

<tf.Tensor: id=21, shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  8,  9],
       [ 4, 10, 18, 28],
       [32, 27, 20, 11]], dtype=int32)>

&emsp;&emsp;按元素除法:

In [0]:
X/Y

<tf.Tensor: id=24, shape=(3, 4), dtype=float64, numpy=
array([[ 0.  ,  1.  ,  0.5 ,  1.  ],
       [ 4.  ,  2.5 ,  2.  ,  1.75],
       [ 2.  ,  3.  ,  5.  , 11.  ]])>

&emsp;&emsp;按元素做指数运算

In [0]:

tf.exp(tf.cast(X,dtype=tf.float32)) #tf1.x 版本eager_execution模式下直接进行exp指数运算会报错，所以先将int32类型转为float32浮点型在计算不会报错

<tf.Tensor: id=26, shape=(3, 4), dtype=float32, numpy=
array([[1.0000000e+00, 2.7182817e+00, 7.3890562e+00, 2.0085537e+01],
       [5.4598148e+01, 1.4841316e+02, 4.0342880e+02, 1.0966332e+03],
       [2.9809580e+03, 8.1030840e+03, 2.2026467e+04, 5.9874141e+04]],
      dtype=float32)>

&emsp;&emsp;除了按元素计算外，我们还可以使用tf.matmul()函数做矩阵乘法。下面将X与Y的转置做矩阵乘法。由于X是3行4列的矩阵，Y转置为4行3列的矩阵，因此两个矩阵相乘后得到3行3列的矩阵。

In [0]:
tf.matmul(X,tf.transpose(Y)) #tf.transpose(Y)矩阵转置函数

<tf.Tensor: id=29, shape=(3, 3), dtype=int32, numpy=
array([[ 18,  20,  10],
       [ 58,  60,  50],
       [ 98, 100,  90]], dtype=int32)>

&emsp;&emsp;我们也可以将多个Tensor连接（concatenate）。下面分别在行上(维度0,即形状中的最左边元素)和列上(维度1，即形状中左起第二个元素)连接两个矩阵。可以看出，输出的第一个Tensor在维度0的长度(6)为两个输入矩阵在维度0的长度之和(3+3)，而输出的第二Tensor同理。

In [0]:
tf.concat((X,Y),axis=0),tf.concat((X,Y),axis=1)

(<tf.Tensor: id=31, shape=(6, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 2,  1,  4,  3],
        [ 1,  2,  3,  4],
        [ 4,  3,  2,  1]], dtype=int32)>,
 <tf.Tensor: id=33, shape=(3, 8), dtype=int32, numpy=
 array([[ 0,  1,  2,  3,  2,  1,  4,  3],
        [ 4,  5,  6,  7,  1,  2,  3,  4],
        [ 8,  9, 10, 11,  4,  3,  2,  1]], dtype=int32)>)

&emsp;&emsp;使用tf.equal()函数可以得到元素为0或为1的新的Tensor。以tf.equal(X,Y)为例，如果X和Y在相同位置的条件判断为真（值相等），那么新的Tensor在相同位置的值为1；反之为0

In [0]:
tf.equal(X,Y)

<tf.Tensor: id=34, shape=(3, 4), dtype=bool, numpy=
array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])>

&emsp;&emsp;对Tensor中的所有元素求和得到只有一个元素的Tensor

In [0]:
tf.reduce_sum(X)

<tf.Tensor: id=36, shape=(), dtype=int32, numpy=66>

&emsp;&emsp;我们可以通过numpy()函数将结果转换为Python中的标量。

In [0]:
tf.reduce_sum(X).numpy()

66

###2.2.3. 广播机制
&emsp;&emsp;前面w们看到如何对两个形状相同的Tensor做按元素运算。当对两个形状不同的Tensor按元素运算时，可能触发广播(broadcasting)机制：先适当复制元素使这两个形状相同后再按元素运算。\
&emsp;&emsp;定义两个Tensor

In [0]:
A=tf.reshape(tf.range(3),shape=(3,1))
B=tf.reshape(tf.range(2),shape=(1,2))
A,B

(<tf.Tensor: id=44, shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]], dtype=int32)>,
 <tf.Tensor: id=50, shape=(1, 2), dtype=int32, numpy=array([[0, 1]], dtype=int32)>)

&emsp;&emsp;由于A和B分别是3行1列和1行2列的矩阵，如果要计算A + B，那么A中第一列的3个元素被广播（复制）到了第二列，而B中第一行的2个元素被广播（复制）到了第二行和第三行。如此，就可以对2个3行2列的矩阵按元素相加。

In [0]:
A+B

<tf.Tensor: id=51, shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]], dtype=int32)>

###2.2.4. 索引
&emsp;&emsp;在在NDArray中，索引（index）代表了元素的位置。NDArray的索引从0开始逐一递增。例如，一个3行2列的矩阵的行索引分别为0、1和2，列索引分别为0和1。

&emsp;&emsp;在下面的例子中，我们指定了NDArray的行索引截取范围[1:3]。依据左闭右开指定范围的惯例，它截取了矩阵X中行索引为1和2的两行。

In [0]:
X[1:3]

<tf.Tensor: id=55, shape=(2, 4), dtype=int32, numpy=
array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

&emsp;&emsp;我们可以指定NDArray中需要访问的单个元素的位置，如矩阵中行和列的索引

In [0]:
X[1,2]

<tf.Tensor: id=59, shape=(), dtype=int32, numpy=6>

&emsp;&emsp;因为tensorflow中Tensor是不可变的，因此直接为张量中的某个元素赋值会报错

In [0]:
X[1,2]=9 #会报错，不支持元素赋值

TypeError: ignored

&emsp;&emsp;可以通过如下方式为张量中的部分元素赋值

In [0]:
XV=tf.Variable(X) #先将Tensor实例转为Variable实例(变量),然后通过tf.assign()函数赋值
XV=tf.assign(XV[1:2,:],tf.constant(12,shape=(1,4)))
XV

<tf.Variable 'UnreadVariable' shape=(3, 4) dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [12, 12, 12, 12],
       [ 8,  9, 10, 11]], dtype=int32)>

###2.2.5. 运算的内存开销
&emsp;&emsp;在前面的例子里我们对每个操作新开内存来存储运算结果。举个例子，即使像Y = X + Y这样的运算，我们也会新开内存，然后将Y指向新内存。为了演示这一点，我们可以使用Python自带的id函数：如果两个实例的ID一致，那么它们所对应的内存地址相同；反之则不同。

In [0]:
before=id(Y)
Y=Y+X
id(Y)==before

False

###2.2.6 Tensor和numpy互换
&emsp;&emsp;我们可以通过array函数和numpy函数令数据在Tensor和NumPy格式之间相互变换。下面将NumPy实例变换成Tensor实例。

In [0]:
import numpy as np
P=np.ones((2,3))
D=tf.constant(P)
D

<tf.Tensor: id=136, shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

&emsp;&emsp;再将Tensor实例变换成Numpy实例

In [0]:
D.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]])

###2.2.8. 特殊张量
TensorFlow中有一些特殊的张量，以下是一些主要的特殊张量：

* tf.Variable（变量，TensorFlow中的张量一般都不会被持久化保存，参与一次运算操作后就会被丢弃了。变量（variable）是一种特殊的运算操作，它可以将一些需要持久化保存的张量存储在内存或显存中，并会返回一个可以对该变量所引用的张量进行一系列特定操作的句柄，例如Assign和AssignAdd（等同于“+=”）等。模型的参数是保存在变量中的，在模型的训练过程中，参数在不断地更新。变量的值可以修改，但是维度不可以变。）
* tf.constant（常量，常量定义时必须初始化值，且定义后其值和维度不可再改变。）
* tf.placeholder（占位符，在执行“session.run()”方法时传入具体的值，TensorFlow2.0中不再使用，但依然可以在“tensorflow.compat.v1”模块中找到。）
* tf.SparseTensor（稀疏张量）

In [0]:
tf.Variable(tf.ones(shape=(3,1)))

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

In [0]:
a=tf.Variable(tf.ones(shape=(3,1)))
tf.assign(a[0,0],3)

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>

In [0]:
b=tf.constant([1,1,1])
b

<tf.Tensor: id=164, shape=(3,), dtype=int32, numpy=array([1, 1, 1], dtype=int32)>

In [0]:
tf.assign(b[2],10) #常量张量不能修改元素

AttributeError: ignored

###2.2.8 小结
（1）Tensor是Tensorflow中存储和变换数据的主要工具 \
（2）可以轻松地对Tensor创建、运算、指定索引